# Lab 1: Welcome to Python!

## Goals
Welcome to your first lab session! In this lab, you will gain hands-on experience with Python programming and learn how Python is used in Data Science.

The first goal of this lab is to ensure that your Python 3 environment is set up correctly and running without issues. If you encounter any problems, please let the tutor know.

This lab will also introduce you to writing your first Python programs, using both scripts and the interactive environment, and applying Python to work with real datasets.

In addition to basic Python concepts, you will begin using Python for basic data analysis tasks, such as loading data, exploring datasets, and performing simple operations that are common in Data Science workflows.

Even if some tasks seem simple, please complete them carefully, as they form the foundation for future labs.

As always, have fun and enjoy the rest of the class period!

## Submission

Name your Jupyter notebook `Group{group number}_week{number}.ipynb`. For example: Group1_week2.ipybn/pdf

## Let's get started!

## Part 1: Basic Python programming

### Loop

**Exercise 1:** Print First 10 natural numbers using while loop

**Expected output:**
````
0
1
2
3
4
5
6
7
8
9
10
````

In [ ]:
# for i in range(10):
#     print(i)

i = 0
while i <= 10:
	print(i)
	i += 1

0
1
2
3
4
5
6
7
8
9
10

### String

**Exercise 2**: Given 2 strings, s1 and s2, concat 2 strings
Given:
````
s1 = "Hello"
s2 = "World"
````
**Expected Output:**
````
    Hello World

````

In [4]:
s1 = "Hello"
s2 = "World"

print (s1 + " " + s2)

Hello World

**Exercise 3**: Removal all the characters other than integers from string
Given:
````
I am 25 years and 10 months old
````
**Expected Output:**
````
2510
````
**Hint: 
- list comprehension,
- Join(),
- isdigit()

In [5]:
given_str = "I am 25 years and 10 months old"

int_only = ''.join(i for i in given_str if i.isdigit())

print(int_only)

2510

### Tuple

**Exercise 4**: Create a tuple with single item 50

**Exercise 4**: Unpack the following tuple into 4 variables
````
aTuple = (10, 20, 30, 40)
````

**Expected output:**

````
aTuple = (10, 20, 30, 40)
# Your code
print(a) # should print 10
print(b) # should print 20
print(c) # should print 30
print(d) # should print 40
````

In [6]:
aTuple = (10, 20, 30, 40)

a, b, c, d = aTuple

print(a)
print(b)
print(c)
print(d)

10
20
30
40

**Exercise 5**: Swap the following two tuples
````
tuple1 = (11, 22)
tuple2 = (99, 88)
````
**Expected output:**
````
tuple1 = (99, 88)
tuple2 = (11, 22)
````

In [9]:
tuple1 = (11, 22)
tuple2 = (99, 88)

tuple1, tuple2 = tuple2, tuple1

print("Tuple 1 =", tuple1)
print("Tuple 2 =", tuple2)

Tuple 1 = (99, 88)
Tuple 2 = (11, 22)

### Set

**Exercise 6**: Add a list of elements to a given set
````
sampleSet = {"Yellow", "Orange", "Black"}
sampleList = ["Blue", "Green", "Red"]
````
**Expected output:**

In set item order is not a concern
````
{'Green', 'Yellow', 'Black', 'Orange', 'Red', 'Blue'}
````
**Hint: use update()

In [10]:
sampleSet = {"Yellow", "Orange", "Black"}
sampleList = ["Blue", "Green", "Red"]

sampleSet.update(sampleList)

print(sampleSet)

{'Yellow', 'Blue', 'Red', 'Black', 'Orange', 'Green'}

**Exercise 7**: Returns a new set with all items from both sets by removing duplicates
````
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
````
**Expected output:**

````
{70, 40, 10, 50, 20, 60, 30}
````
Remember set is unordered so not necessary this will be the order of the item.

In [13]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}

no_duplicate = set1.union(set2)

print(no_duplicate)

{70, 40, 10, 50, 20, 60, 30}

### Dictionaries

**Exercise 8**: Below are the two lists convert it into the dictionary
````
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
````
**Expected output:**

````
{'Ten': 10, 'Twenty': 20, 'Thirty': 30}````

In [14]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]

result = {}
for i, key in enumerate(keys):
    result[key] = values[i]

print(result)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

**Exercise 9**: Merge following two Python dictionaries into one
````
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
````
**Expected output:**

````
{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
````

In [15]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

merge_dict = dict1.copy()
merge_dict.update(dict2)

print(merge_dict)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

## Mixed parts

**Exercise 10:** Write a loop to find the factorial of any number
The factorial (symbol: !) means to multiply all whole numbers from our chosen number down to 1.

**For example:** calculate the factorial of 5

5! = 5 × 4 × 3 × 2 × 1 = 120

**Expected output:**
````
120
````

In [17]:
num = 5

factorial = 1
for i in range(1, num + 1):
	factorial *= i

print(factorial)

120

**Exercise 11:** Reverse a given integer number
Given:
````
76542
````

**Expected output:**
````
24567
````

In [ ]:
given_num = 76542

reversed_num = int(str(given_num)[::-1])
print(reversed_num)

**Exercise 12:** Find the sum of the series 2 +22 + 222 + 2222 + .. n terms

Given:
````
number_of_terms = 5
````
So series will become 2 + 22 + 222 + 2222 + 22222

**Expected output:**
````
24690
````

In [22]:
number_of_terms = 5

num = 2
result = 0

for i in range(number_of_terms):
	result += num
	num = num * 10 + 2

print(result)

24690

**Exercise 13:** Create a function that can accept two arguments name and age and print its value

In [23]:
def sum_num (num1, num2):
	return num1 + num2

print(sum_num(10, 20))

30

**Exercise 14:** Write a function func1() such that it can accept a variable length of  argument and print all arguments value
````
func1(20, 40, 60)
func1(80, 100)
````

**Expected Output:**

After func1(20, 40, 60):
````
20
40
60
````

After func1(80, 100):
````
80
100
````

In [ ]:
def fun1 (a = None, b = None, c = None):
	if a is not None:
		print(a)
	if b is not None:
		print(b)
	if c is not None:
		print(c)

print("After fun1(10, 20, 30):")
fun1(10, 20, 30)
print("After fun1(80, 100):")
fun1(80, 100)

After fun1(10, 20, 30):
10
20
30
After fun1(80, 100):
80
100

**Exercise 15:** Create a function showEmployee() in such a way that it should accept employee name, and it’s salary and display both, and if the salary is missing in function call it should show it as 9000

**Expected Output:**
````
showEmployee("Ben", 9000)
showEmployee("Ben")
````

Should Produce:
````
Employee Ben salary is: 9000
Employee Ben salary is: 9000
````

In [27]:
def showEmployee (emp_name, salary = 9000):
	print("Employee", emp_name, "salary is:", salary)

showEmployee("Ben", 9000)
showEmployee("Ben")

Employee Ben salary is: 9000
Employee Ben salary is: 9000

**Exercise 16:** Given a two integer numbers return their product and  if the product is greater than 1000, then return their sum

Given:

````
number1 = 20
number2 = 30
````

Expected Output:

`````
The result is 600
````
Given:
````
number1 = 40
number2 = 30
````
Expected Output:
````
The result is 70
````

In [29]:
def product (num1, num2):
	if num1 * num2 > 1000:
		return num1 + num2
	return num1 * num2

number1 = 20
number2 = 30

print(product(number1, number2))

number1 = 40
number2 = 30

print(product(number1, number2))

600
70

**Exercise 17**: Given a two list of equal size create a set such that it shows the element from both lists in the pair

**Expected Output:**
````
First List  [2, 3, 4, 5, 6, 7, 8]
Second List  [4, 9, 16, 25, 36, 49, 64]
Result is  {(6, 36), (8, 64), (4, 16), (5, 25), (3, 9), (7, 49), (2, 4)}
````
**Hint: use zip()

In [35]:
list1 = [2, 3, 4, 5, 6, 7, 8]
list2 = [4, 9, 16, 25, 36, 49, 64]

result = set(zip(list1, list2))

print(result)

{(7, 49), (2, 4), (4, 16), (8, 64), (6, 36), (3, 9), (5, 25)}

**Exercise 18:** Given a range of first 10 numbers, Iterate from start number to the end number and print the sum of the current number and previous number

Reference article for help:
- [Python range() function](https://pynative.com/python-range-function/)
- [Calculate sum and average in Python](https://pynative.com/python-program-to-calculate-sum-and-average-of-numbers/)

**Expected Output:**
````
Printing current and previous number sum in a given range(10)
Current Number 0 Previous Number  0  Sum:  0
Current Number 1 Previous Number  0  Sum:  1
Current Number 2 Previous Number  1  Sum:  3
Current Number 3 Previous Number  2  Sum:  5
Current Number 4 Previous Number  3  Sum:  7
Current Number 5 Previous Number  4  Sum:  9
Current Number 6 Previous Number  5  Sum:  11
Current Number 7 Previous Number  6  Sum:  13
Current Number 8 Previous Number  7  Sum:  15
Current Number 9 Previous Number  8  Sum:  17
````

In [4]:
print("Printing current and previous number sum in a given range(10)")
for i in range(10):
	if i == 0:
		i = 1
	print("Current Number", i, "Previous Number", i - 1, "Sum:", i + (i - 1))

Printing current and previous number sum in a given range(10)
Current Number 1 Previous Number 0 Sum: 1
Current Number 1 Previous Number 0 Sum: 1
Current Number 2 Previous Number 1 Sum: 3
Current Number 3 Previous Number 2 Sum: 5
Current Number 4 Previous Number 3 Sum: 7
Current Number 5 Previous Number 4 Sum: 9
Current Number 6 Previous Number 5 Sum: 11
Current Number 7 Previous Number 6 Sum: 13
Current Number 8 Previous Number 7 Sum: 15
Current Number 9 Previous Number 8 Sum: 17

**Exercise 19**: Delete set of keys from Python Dictionary
Given:
````
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
  
}
keysToRemove = ["name", "salary"]
````
**Expected output:**

````
{'city': 'New york', 'age': 25}
````

In [5]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
  
}
keysToRemove = ["name", "salary"]

for key in keysToRemove:
	sampleDict.pop(key)

print(sampleDict)

{'age': 25, 'city': 'New york'}

**Exercise 20:** Given a string, display only those characters which are present at an even index number.
For example str = "pynative" so you should display ‘p’, ‘n’, ‘t’, ‘v’.

Reference article for help: Python Input and Output

**Expected Output:**
````
Orginal String is  pynative
Printing only even index chars
p
n
t
v
````

In [6]:
given_str = "pynative"
print("Original String:", given_str)

print("Printing only even index chars:")
for i in range(len(given_str)):
	if i % 2 == 0:
		print(given_str[i])

Original String: pynative
Printing only even index chars:
p
n
t
v

**Exercise 21:** Given a list of numbers, return True if first and last number of a list is same

**Expected Output:**
````
Given list is  [10, 20, 30, 40, 10]
result is True
Given list is  [10, 20, 30, 40, 50]
result is False
````

In [7]:
list1 = [10, 20, 30, 40, 10]
list2 = [10, 20, 30, 40, 50]

print("Given list is", list1)
if list1[-1] == list1[0]:
	print("result is True")
else:
	print("result is False")

print("Given list is", list2)
if list2[-1] == list2[0]:
	print("result is True")
else:
	print("result is False")

Given list is [10, 20, 30, 40, 10]
result is True
Given list is [10, 20, 30, 40, 50]
result is False

**Exercise 22:** Given a list of numbers, Iterate it and print only those numbers which are divisible of 5

**Expected Output:**
````
Given list is  [10, 20, 33, 46, 55]
Divisible of 5 in a list
10
20
55
````

In [8]:
given_list = [10, 20, 33, 46, 55]

print("Given list is", given_list)
print("Divisible by 5 in a list")

for i in given_list:
	if i % 5 == 0:
		print(i)

Given list is [10, 20, 33, 46, 55]
Divisible by 5 in a list
10
20
55

**Exercise 23:** Return the total count of sub-string “Emma” appears in the given string

Given string is “Emma is good developer. Emma is a writer”

**Expected Output:**
````
Emma appeared 2 times
````

In [9]:
given_str = "Emma is good developer. Emma is a writer"

print("Emma appeared", given_str.count("Emma"), "times")

Emma appeared 2 times

**Exercise 24:** Print the following pattern
````
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5
````

In [20]:
for i in range(1, 5):
	for j in range(i):
		print(i, "", end="")
	print()

1
2 2
3 3 3
4 4 4 4

**Exercise 25:** Print downward Half-Pyramid Pattern with Star (asterisk)

````
* * * * *  
* * * *  
* * *  
* *  
*
````

In [23]:
for i in range(5, 0, -1):
	print(i * "* ")

* * * * *
* * * *
* * *
* *
*

**Exercise 26:** Write a function called exponent(base, exp) that returns an int value of base raises to the power of exp.
Note here exp is a non-negative integer, and the base is an integer.

**Expected Output:**

Case 1:

base = 2
exponent = 5

2 raises to the power of 5 is: 32 i.e. (2 *2 * 2 *2 *2 = 32)

Case 2:

base = 5
exponent = 4

5 raises to the power of 4 is: 625 i.e. (5 *5 * 5 *5 = 625)

In [50]:
## calculate exponent function
def exponent(base, exp):
	if exp < 0:
		print("Exp should be non-negative integer")
		return 1

	result = base ** exp

	return result

## Case 1
print("Case 1:")
base = 2
exp = 5
print("base =", base, "exp =", exp)
## call function
result = exponent(base, exp)

ie = str(base)
for i in range(exp - 1):
	ie += "*" + str(base)

ie += "=" + str(result)
## result display
if exp >= 0:
	print(base, " raises to the power of ", exp, " is: ", result, " i.e. (", ie, ")", sep="")


## Case 2
print("Case 2:")
base = 5
exp = 4
print("base =", base, "exp =", exp)
## call function
result = exponent(base, exp)

ie = str(base)
for i in range(exp - 1):
	ie += "*" + str(base)

ie += "=" + str(result)
## result display
if exp >= 0:
	print(base, " raises to the power of ", exp, " is: ", result, " i.e. (", ie, ")", sep="")

Case 1:
base = 2 exp = 5
2 raises to the power of 5 is: 32 i.e. (2*2*2*2*2=32)
Case 2:
base = 5 exp = 4
5 raises to the power of 4 is: 625 i.e. (5*5*5*5=625)

## Part 2: Python for Data science

import pandas as pd

df = pd.read_csv("data.csv")
df.head()

In [ ]:
import pandas as pd

df = pd.read_csv('telegram_spam_cleaned.csv')
df.head(10)

,id,date,text,label,has_media,forwarded_from
0,2,2025-04-04T15:01:47,Срочно требуются 2 человека. Прибыльность от 1...,spam,0,0
1,3,2025-04-04T15:01:47,Выходи на доход от 80 долларов в час. Есть нес...,spam,0,0
2,4,2025-04-04T15:27:55,Здрастуйте. Доход от 500 доларов в неделю. Ест...,spam,0,0
3,5,2025-04-04T15:28:13,Требуются 2 человека. Заработок от 16 тыс. руб...,spam,0,0
4,6,2025-04-04T15:42:57,Срочно ищем новых партнеров для УДАЛЕННОГО зар...,spam,0,0
5,7,2025-04-04T16:44:15,Срочно ищем новых партнеров для УДАЛЕННОГО зар...,spam,0,0
6,8,2025-04-04T20:40:38,Здравствуйте. Хорошая возможность получать 400...,spam,0,0
7,9,2025-04-04T20:40:38,Нужны люди в команду. Приятный ЗАРАБОТОК от 20...,spam,0,0
8,10,2025-04-04T20:40:38,Нужны люди в команду. Приятный ЗАРАБОТОК от 20...,spam,0,0
9,11,2025-04-04T20:40:38,Нужны люди в команду. Приятный ЗАРАБОТОК от 20...,spam,0,0

**Discussion 1**:
````
1. Why do we load data instead of typing it manually?
- Dataset contains many rows and long text messages
- Manual typing would be slow and error-prone
- Loading ensures accuracy and efficiency

2. What does each row represent?
- Each row represent about one telegram message record

3. What does each column represent?
- Information about each message (ID, date, text, label, has_media , forward_from)

4. Why do we look at the first few rows?
- To understand structure and content
- To verify data loaded correctly
````

In [6]:
df.shape
df.columns

Index(['id', 'date', 'text', 'label', 'has_media', 'forwarded_from'], dtype='object')

**Discussion 2**:
````
1.What does one row represent in this dataset?
- One row represented one spam message that was sent at a specific date and time.

2. What does one column represent?
- One column represented a specific attribute of a spam message.

3. Why is it important to know the number of rows and columns before analysis?
- Knowing the number of rows and columns before analysis allows you to plan your data processing
effectively (memory, method, visualization choices, storage, and pipeline design).

4. How many observations are in the dataset?
- There are 199 reservations in this dataset.

5. Which columns are numeric? Which are categorical?
- Numeric: ID
Categorical: Has_media, Forwarded_from, Label
````

In [7]:
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              199 non-null    int64
 1   date            199 non-null    object
 2   text            199 non-null    object
 3   label           199 non-null    object
 4   has_media       199 non-null    int64
 5   forwarded_from  199 non-null    int64
dtypes: int64(3), object(3)
memory usage: 9.5+ KB

**Discussion 3**:
````
1. Why is knowing data types important in data analysis?
- Helps understand dataset size
- Guides choice of analysis methods

2. What problems can happen if data types are incorrect?
- Wrong results, calculation errors, failed models, sorting/filtering issues, and
misleading insights.

3. Are there any missing values?
- No missing value

4. Which columns might need cleaning?
- This is an ISO datetime string, Needs conversion to Sort data by time.
````

In [8]:
df.describe()

               id   has_media  forwarded_from
count  199.000000  199.000000      199.000000
mean   107.693467    0.015075        0.331658
std     61.778208    0.122160        0.471996
min      2.000000    0.000000        0.000000
25%     54.500000    0.000000        0.000000
50%    109.000000    0.000000        0.000000
75%    158.500000    0.000000        1.000000
max    215.000000    1.000000        1.000000

**Discussion 4**:
````
1. What does average (mean) tell us about data?
- Mean (average) → shows the typical value of a variable.
has_media mean 0.015 → almost no messages have media.

2. Why might min and max be misleading sometimes?
- can be misleading if most values are far from them or there are
outliers.

3. Which variable has the highest average?
- forwarded_from

4. Are there any unusual values?
- forwarded_from: mean is 0.332, but 25% and 50% are 0 →
indicates many zeros and some ones, which is typical for a binary
variable but shows skewness.
````

In [12]:
df_forwarded = df[df["forwarded_from"] != 0]
df_forwarded

,id,date,text,label,has_media,forwarded_from
20,25,2025-04-07T14:59:55,👄🥺Загляни ко мне в профиль🥺👄,spam,0,1
26,31,2025-04-07T17:00:19,Ищем активных людей для стабильного дохода! За...,spam,0,1
27,32,2025-04-07T19:33:15,Готов к доходу от $700 в неделю? Уникальные ус...,spam,0,1
29,34,2025-04-07T19:33:15,ищу ᴧюдᴇй дᴧя ᴄᴏᴛᴩудничᴇᴄᴛʙᴀ ʙ нᴏʙᴏʍ ᴨᴩᴏᴇᴋᴛᴇ (...,spam,0,1
30,35,2025-04-07T19:33:15,Выиграл 988кк с нуля в новом боте:,spam,0,1
...,...,...,...,...,...,...
193,210,2025-10-11T15:44:27,Ищем людей для удалённой деятельности на Binan...,spam,0,1
194,211,2025-10-11T15:44:27,Ищем людей для удалённой деятельности на Binan...,spam,0,1
195,212,2025-10-16T14:31:52,Ищем людей для удалённой деятельности на Binan...,spam,0,1
196,213,2025-10-20T13:29:53,💼 Свежий онлайн-проект — набираю людей в коман...,spam,0,1
197,214,2025-10-30T20:03:53,Всем привет!\nНаша команда находится в поиске ...,spam,0,1

**Discussion 5**:
````
1. Why might we want to remove some rows from a dataset?
- To delete errors or missing data and make analysis more accurate.

2. What is the difference between cleaning data and losing data?
- Cleaning data means fixing or improving data without removing useful
- Losing data means removing or discarding data in a way that reduces
information or value.

3. How many rows were removed?
- None
````